name: Go Test Setup
description: Set up the environment for go test
runs:
  using: "composite"
  steps:
    - name: Install filecoin-ffi dependencies
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y libhwloc-dev ocl-icd-opencl-dev
    - name: Install filecoin-ffi
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: make extern/filecoin-ffi
    # Removes all go test files to stop the unified CI from running ffi tests as part of the build.
    # See: https://github.com/protocol/multiple-go-modules/issues/11
    - name: Remove filecoin-ffi tests
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: find extern/filecoin-ffi -name '*_test.go' -exec rm {} \;